config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post ':family_id/join_family', to: 'kinship#create', as: 'join_family'
  post ':family_id/leave_family', to: 'kinship#destroy', as: 'leave_family'

	resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  resources :users

	root 'sessions#new'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def index
    @comments = @post.comments.order("created_at ASC")

    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

  def create
    @comment = @post.comments.build(params_for_comments)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = 'Comment could not be added.'
      render root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if current_user.id == @comment.user_id
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private

    def params_for_comments
      params.require(:comment).permit(:content)
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div>
  <div class="comment-user-name">
    <%= link_to comment.user.first_name + ' ' + comment.user.last_name, user_path(comment.user), class: 'comment-user-name' %>
  </div>
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
      <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
          <span class="glyphicon glyphicon-remove-circle delete-comment"></span>
      <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append('<%= j render 'comments/comment', post: @post, comment: @comment %>');
$('#comment_content_<%= @post.id %>').val('');

app/views/comments/destroy.js.erb
$("#comments_<%= @post.id %>").html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/comments/index.html.erb
<%= render @comments, post: @post %>