config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post ':family_id/join_family', to: 'kinship#create', as: 'join_family'
  post ':family_id/leave_family', to: 'kinship#destroy', as: 'leave_family'

	resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  resources :users

	root 'sessions#new'

end

app/models/user.rb
class User < ApplicationRecord
  include AuthenticationHelper

  acts_as_voter

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :kinship
  has_many :family, through: :kinship

  attr_accessor :remember_token

  before_save {self.email.downcase!}

  has_attached_file :image, styles: { thumb: '50x50', medium: '250x250', large: '400x400' }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :first_name, presence: true, length: {maximum: 20}
  validates :last_name, presence: true, length: {maximum: 20}

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: EMAIL_REGEX}, uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  validates :bio, length: {maximum: 500}

  # remember user in database for use in persistent session
  def remember
    self.remember_token = new_token
    update_attribute(:remember_digest, digest(remember_token))
  end

  # forget a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # return true if the given token matches the digest
  def authenticated?(token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user?, only: [:edit, :update, :destroy, :show, :index]
  before_action :correct_user?, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:edit, :update, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_for_user)
    if @user.save
      login @user
      redirect_to_forwarding_url_or user_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user.update_attribute(:image, params[:user][:image])
    @user.update_attribute(:bio, params[:user][:bio])
      flash[:success] = 'Profile updated!'
      redirect_to user_path(@user)
  end

  def show
    @posts = @user.posts.order(:date).reverse_order.page params[:page]
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User removed.'
    redirect_to login_path
  end

  def index
    @users = User.all.order('last_name').page params[:page]
  end

  private

    # strong params for mass assignment vulnerability prevention
    def params_for_user
      params.require(:user).permit(:first_name, :last_name, :email, :image, :password, :password_confirmation, :bio)
    end

    def correct_user?
      @user = User.find(params[:id])
      redirect_to root_url if !current_user?(@user)
    end

    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/users_helper.rb
module UsersHelper

  def current_user_is_family(family_id)
    kinship =  Kinship.find_by(user_id: current_user.id, family_id: family_id)
    return true if kinship
  end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

    <%= f.email_field :email, placeholder: 'Email', class: 'form-control' %>

    <%= f.text_field :first_name, placeholder: 'First Name', class: 'form-control' %>

    <%= f.text_field :last_name, placeholder: 'Last Name', class: 'form-control' %>

    <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>

    <%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'form-control' %>

    <%= f.submit message, class: 'btn btn-main' %>
<% end %>

app/views/users/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <h1 align="center">Update your profile</h1>
        <%= form_for @user, url: {action: 'update'}, html: { multipart: true } do |f| %>
            <%= render 'shared/error_message' %>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group text-center">
                  <h4>Change your profile image:</h4>
                    <%= profile_pic_select(@user, 'edit') %>
                  <%= f.file_field :image, onChange: 'loadFile(event)' %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group text-center">
                  <h4>Update your bio:</h4>
                  <%= f.text_area :bio, label: false, rows: 4, placeholder: 'Tell us a little about yourself...' %>
                </div>
              </div>
            </div>
            <div class="form-group text-center">
              <%= f.submit 'Update Profile', class: 'btn btn-main' %>
            </div>
            <div class="form-group text-center">
              <%= link_to 'Delete user', user_path, method: :delete, class: 'delete-links', data: { confirm: 'Are you sure?' } %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="posts-wrapper">
  <div class="post">
    <h1 class="text-center empty-index-text">Find Family</h1>
    <ul class="users">
      <% @users.each do |user| %>
          <div class="post-top">
            <div class="row col-md-9">
              <div class="post-pic col-md-2">
                <%= profile_pic_select(user, 'post') %>
              </div>
              <div class="user-name col-md-10">
                <%= link_to user.first_name + ' ' + user.last_name, user_path(user), class: 'user-name' %>
              </div>
            </div>
          </div>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/new.html.erb
<div class="registration-background">
  <div class="container">
      <div class="col-md-6 col-md-offset-3">
        <div class="log-in panel">
          <div class="panel-heading">
            <% unless @user.errors.any? %>
              <%= image_tag('legacy-logo-circle.jpg') %>
            <% end %>
            <h2>Create an account</h2>
          </div>
          <div class="panel-body">
            <%= render 'shared/error_message' %>

            <%= render partial: 'form', :locals => {:message => 'Create your account'} %>

            <p>Already registered? <%= link_to 'Log in now!', login_path %></p>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-4">
      <div class="img-circle">
        <%= profile_pic_select(@user, 'profile') %>
      </div>
    </div>
    <div class="col-md-8">
      <div class="user-name-and-family row">
        <h3 class="profile-user-name col-md-6">
          <%= @user.first_name + ' ' + @user.last_name %>
        </h3>
        <span class="col-md-6 edit-leave-join">
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn join-family-button' %>
          <% else %>
              <% if current_user_is_family(@user.id) %>
                <%= link_to 'Leave Family', leave_family_path(family_id: @user.id), remote: true, class: 'btn leave-family-button', id: 'leave-family-button', method: 'post' %>
              <% else %>
                <%= link_to 'Join Family', join_family_path(family_id: @user.id), remote: true, class: 'btn join-family-button', id: 'join-family-button', method: 'post' %>
              <% end %>
          <% end %>
        </span>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      <div class="user-statistics">
        <p class="num-memories">
          <%= pluralize @user.posts.count, 'memory' %>
        </p>
      </div>
    </div>
  </div>
</div>

<div id="post-index">
  <%= render 'posts/posts' %>
</div>

<% if @user.posts.all.count > 3 %>
    <div class="text-center" id="paginator">
      <%= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
    </div>
<% end %>

app/views/users/show.js.erb
var $paginator = $('#paginator');

$('#post-index').append("<<%= escape_javascript(render 'posts/posts')%>>");
$paginator.html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $paginator.html("<a id='load_more'>END OF POSTS</a>"); }