config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post ':family_id/join_family', to: 'kinship#create', as: 'join_family'
  post ':family_id/leave_family', to: 'kinship#destroy', as: 'leave_family'

	resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  resources :users

	root 'sessions#new'

end

app/models/post.rb
class Post < ApplicationRecord

  acts_as_votable

	belongs_to :user
	has_many :comments, dependent: :destroy

	validates :image, presence: true
	validates :user_id, presence: true
  validates :date, presence: true
  validates :caption, length: {maximum: 2000}

	has_attached_file :image, styles: { :medium => '640x' }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	scope :of_family_members, -> (family_members) { where user_id: family_members }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user?
	before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
	before_action :owns_post?, only: [:edit, :update, :destroy]

	def index
		@total_posts = Post.of_family_members(current_user.family).count
		@posts = Post.of_family_members(current_user.family).order(:date).reverse_order.page params[:page]
	end
	
	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(params_for_post)
		if @post.save
			flash[:success] = 'Post created!'
			redirect_to posts_path
		else
			flash.now[:alert] = 'Post could not be created. Missing necessary information.'
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update(params_for_post)
			flash[:success] = 'Post updated!'
			redirect_to(post_path(@post))
		else
			flash[:alert] = 'Post could not be updated. Missing necessary information.'
			render :edit
		end
	end

	def destroy
		if @post.destroy
			flash[:success] = 'Post deleted!'
			redirect_to posts_path
		end
	end

	def like
		if @post.liked_by current_user
			respond_to do |format|
				format.html { redirect_back }
				format.js
			end
		end
	end

	def unlike
		if @post.unliked_by current_user
			respond_to do |format|
				format.html { redirect_back }
				format.js
			end
		end
	end

	private

	def params_for_post
		params.require(:post).permit(:image, :caption, :date)
	end

	def set_post
		@post = Post.find(params[:id])
	end

	def owns_post?
		unless current_user?(@post.user)
			redirect_to root_path
		end
	end

end

app/helpers/posts_helper.rb
module PostsHelper

  def display_form_image_or_placeholder(post)
    if post.image.exists?
      image_tag(post.image.url(:medium), id: 'image-preview', class: 'img-responsive ')
    else
      image_tag('placeholder-post-img.jpg', id: 'image-preview', class: 'img-responsive ')
    end
  end

  def likers_of(post)
    votes = post.votes_for.up.by_type(User)
    users = []
    unless votes.blank?
      votes.voters.each do |voter|
        users.push(link_to voter.first_name + ' ' + voter.last_name,
                                user_path(voter),
                                class: 'user-name-like')
      end
      return 'Liked by '.html_safe + likers_condensed(users)
    end
  end

  def likers_condensed(users)
    if users.length > 3
      user_count = users.count
      return "#{users.count} likes"
    else
      return users.to_sentence.html_safe
    end
  end

  def like_status(post)
    if current_user.voted_for? post
      return link_to '', unlike_post_path(post), remote: true, id: "like_#{post.id}", class: 'glyphicon glyphicon-heart liked-button'
    else
      return link_to '', like_post_path(post), remote: true, id: "like_#{post.id}", class: 'glyphicon glyphicon-heart-empty like-button'
    end
  end

end

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="image center-block" align="middle">
      <%= display_form_image_or_placeholder(@post) %>
    </div>
    <div class="container-fluid post-upload-form">
      <%= form_for(@post) do |f| %>

          <%= f.label :image %>
          <%= f.file_field :image, onChange: 'loadFile(event)' %>

          <%= f.text_area :caption, placeholder: 'Tell your story...', rows: 5, class: 'form-control' %>

          <%= f.date_select(:date, start_year: 1900, end_year: Date.today.year) %>

          <%= f.submit message, class: 'btn btn-main' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_likes.html.erb
<div id="likes_<%= post.id %>" class="likes col-sm-11">
  <%= likers_of post %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-top">
      <div class="row col-md-9">
        <div class="post-pic col-md-2">
          <%= profile_pic_select(post.user, 'post') %>
        </div>
        <div class="user-name col-md-10">
          <%= link_to post.user.first_name + ' ' + post.user.last_name, user_path(post.user), class: 'user-name' %>
        </div>
      </div>
      <div class="time-ago"><%= post.date.to_formatted_s(:long_ordinal) %></div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="row likes-box">
        <div class="col-sm-1 like-button-area">
          <%= like_status post %>
        </div>
        <%= render 'posts/likes', post: post %>
      </div>
      <div class="caption">
          <div>
            <%= link_to post.user.first_name + ' ' + post.user.last_name, user_path(post.user), class: 'caption-user-name' %>
          </div>
          <div class="caption-content">
            <%= post.caption %>
          </div>
      </div>
      <div class="comments" id="comments_<%= post.id %>">
        <% if post.comments.any? %>
            <div class="paginator" id="#comments-paginator-<%= post.id %>">
              <% unless post.comments.count <= 4 %>
                  <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: {post_id: "#{post.id}", type: "html"} %>
              <% end %>
            </div>
            <%= render post.comments.last(4), post: post %>
        <% end %>
      </div>
    </div>
    <div class="comment-like-form row">
      <div class="comment-form col-sm-11">
        <%= form_for([post, post.comments.build], remote: true) do |f| %>
            <%= f.text_field :content, placeholder: 'Add a comment...', class: 'comment-content', id: "comment_content_#{post.id}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
    <%= render 'posts/post', post: post %>
<% end %>

app/views/posts/edit.html.erb
<%= render partial: 'form', :locals => {:message => 'Edit your post'} %>
<div class="text-center">
  <%= link_to 'Delete post', post_path(@post), method: :delete, class: 'delete-links', data: { confirm: "Are you sure you want to delete this post?" } %>
</div>

app/views/posts/index.html.erb
<% if current_user.family.count != 0 %>
    <div id="post-index">
      <%= render 'posts' %>
    </div>

    <% if @total_posts > 3 %>
        <div class="text-center" id="paginator">
          <%= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
        </div>
    <% end %>
<% else %>
    <div class="posts-wrapper">
      <%= image_tag('legacy-logo-circle-grey-background.jpg', class: 'empty-index-logo') %>
      <h1 class="empty-index-text text-center">
        Add family members to see their memories here.
      </h1>
      <h1 class="empty-index-text text-center">
        Use the <span><%= link_to 'Explore', users_path, class: 'empty-index-explore-link' %></span> page to search for relatives!
      </h1>
    </div>
<% end %>

app/views/posts/index.js.erb
$('#post-index').append("<<%= escape_javascript(render 'posts')%>>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').html("<a id='load_more'>END OF POSTS</a>"); }

app/views/posts/like.js.erb
$('#like_<%= @post.id %>').removeClass('glyphicon-heart-empty like-button').addClass('glyphicon-heart liked-button');
$("#like_<%= @post.id %>").attr('href', '/posts/<%= @post.id %>/unlike');
$('#likes_<%= @post.id %>').html('<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>');

app/views/posts/new.html.erb
<%= render partial: 'form', :locals => {:message => 'Create your post'} %>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<div class="text-center edit-links">
  <% if current_user.id == @post.user.id %>
      <%= link_to 'Edit Post', edit_post_path(@post), class: 'btn join-family-button' %>
  <% end %>
</div>

app/views/posts/unlike.js.erb
$('#like_<%= @post.id %>').removeClass('glyphicon-heart liked-button').addClass('glyphicon-heart-empty like-button');
$("#like_<%= @post.id %>").attr('href', '/posts/<%= @post.id %>/like');
$('#likes_<%= @post.id %>').html('<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>');