config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post ':family_id/join_family', to: 'kinship#create', as: 'join_family'
  post ':family_id/leave_family', to: 'kinship#destroy', as: 'leave_family'

	resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  resources :users

	root 'sessions#new'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="glyphicon glyphicon-menu-hamburger"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to (image_tag('legacy-logo-circle-min.jpg', size: '55')), posts_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if logged_in? %>
              <a href=<%=new_post_path%>><span class="glyphicon glyphicon-upload"></span> New Post</a>
          <% end %>
        </li>
        <li>
          <% if logged_in? %>
              <a href=<%=user_path(current_user)%>><span class="glyphicon glyphicon-user"></span> Profile</a>
          <% else %>
              <a href=<%=login_path%>><span class="glyphicon glyphicon-log-in"></span> Login</a>
          <% end %>
        </li>
        <li>
          <% if logged_in? %>
              <a href=<%=users_path%>><span class="glyphicon glyphicon-globe"></span> Explore</a>
          <% end %>
        </li>
        <li>
          <% if logged_in? %>
              <a href=<%=logout_path%> data-method="delete"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
          <% else %>
              <a href=<%=new_user_path%>><span class="glyphicon glyphicon-globe"></span> Register</a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <% unless (controller_name == 'sessions' && (action_name == 'new' || action_name == 'create')) ||
            (controller_name == 'users' && (action_name == 'new' || action_name == 'create')) %>
    <%= render 'layouts/navbar' %>
  <% end %>

  <title>legacy</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <div class="container">
    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
    <% end %>
  </div>

 <body>
 	<%= yield %>
 </body>

</html>